fix: Update workflows/kemono-all2discord.yml

diff --git a/workflows/kemono-all2discord.yml b/workflows/kemono-all2discord.yml
--- a/workflows/kemono-all2discord.yml
+++ b/workflows/kemono-all2discord.yml
@@ -23,17 +23,30 @@ jobs:
           userId=$(awk -F "/" '{print $6}' <<<"${{ on.poll.outputs.contentUrl }}")
           contentId=$(awk -F "/" '{print $8}' <<<"${{ on.poll.outputs.contentUrl }}")
           fix_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}"
+          oembed_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}/oembed.json"
           echo "::set-output name=title::${fix_title}"
           echo "::set-output name=link::${fix_url}"
+          echo "::set-output name=oembed::${oembed_url}"
       - name: Post
         run: |
           {
-            imageUrl=$(curl -s --retry 10 --retry-all-errors -H 'User-Agent: Discordbot' ${{ steps.fix.outputs.link }}|grep 'property="og:image"'|sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
-            curl -s \
-                 --retry 10 \
-                 --retry-all-errors \
-                 --max-time 10
-                 "${imageUrl}" > /dev/null 2>&1 || :
+            # imageUrl=$(curl -s --retry 10 --retry-all-errors -H 'User-Agent: Discordbot' ${{ steps.fix.outputs.link }}|grep 'property="og:image"'|sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
+            # curl -s \
+            #      --retry 10 \
+            #      --retry-all-errors \
+            #      --max-time 10
+            #      "${imageUrl}" > /dev/null 2>&1 || :
+            for i in {1..10}; do
+              curl -s \
+                   --retry 10 \
+                   --retry-all-errors \
+                   -H 'User-Agent: Discordbot' \
+                   ${{ steps.fix.outputs.link }} > /dev/null 2>&1 || :
+              curl -s \
+                   --retry 10 \
+                   --retry-all-errors \
+                   ${{ steps.fix.outputs.oembed }} > /dev/null 2>&1 || :
+            done
             curl -s \
                  -X POST \
                  --retry 10 \
