fix: Update workflows/kemono-*.yml

diff --git a/workflows/kemono-fanbox2discord-04.yml b/workflows/kemono-fanbox2discord-04.yml
--- a/workflows/kemono-fanbox2discord-04.yml
+++ b/workflows/kemono-fanbox2discord-04.yml
@@ -50,18 +50,18 @@ jobs:
           fix_title=$(echo '${{ on.poll.outputs.title }}' | sed "s/'/'\\\''/g" | sed 's/!/\\!/g;s/"/\\"/g;s/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
           sourseName=$(awk -F "/" '{print $4}' <<<"${{ on.poll.outputs.contentUrl }}")
           userId=$(awk -F "/" '{print $6}' <<<"${{ on.poll.outputs.contentUrl }}")
-          contentId=$(awk -F "/" '{print $8}' <<<"${{ on.poll.outputs.contentUrl }}")
+          contentId=$(awk -F "/" '{print $7}' <<<"${{ on.poll.outputs.contentUrl }}")
           fix_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}"
           echo "::set-output name=title::${fix_title}"
           echo "::set-output name=link::${fix_url}"
       - name: Post
         run: |
           {
-            imageUrl=$(curl -s --retry 10 --retry-all-errors -H 'User-Agent: Discordbot' "${{ steps.fix.outputs.link }}" | grep 'property="og:image"' | sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
-            curl -s \
-                 --retry 10 \
-                 --retry-all-errors \
-                 "${imageUrl}" > /dev/null 2>&1 || :
+            # imageUrl=$(curl -s --retry 10 --retry-all-errors -H 'User-Agent: Discordbot' "${{ steps.fix.outputs.link }}" | grep 'property="og:image"' | sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
+            # curl -s \
+            #      --retry 10 \
+            #      --retry-all-errors \
+            #      "${imageUrl}" > /dev/null 2>&1 || :
             curl -s \
                  -X POST \
                  --retry 10 \
